
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wordpress.secret.name }}
type: Opaque
data:
  host: {{ .Values.wordpress.secret.host | b64enc }}
  password: {{ .Values.wordpress.secret.password | b64enc }}
  user: {{ .Values.wordpress.secret.user | b64enc }}
  database: {{ .Values.wordpress.secret.database | b64enc }}