apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql 
  labels:
    app: wordpress
    tier: mysql
spec:
  type: ClusterIP 
  clusterIP: None  
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: wordpress
    tier: mysql


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-wordpress
  labels:
    app: wordpress
    tier: mysql
spec:
  replicas: {{ .Values.mysql.deployment_replicas }}
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: {{ .Values.mysql.deployment_image }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - protocol: TCP
          containerPort: 3306